import ThemeRegistry from "../components/ThemeRegistry/ThemeRegistry";
import Header from "../components/Header";
import "./globals.css";
import { skyscannerRelative } from "./font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${skyscannerRelative.variable} ${skyscannerRelative.className}`}>
      <body>
        <ThemeRegistry>
          <Header />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
